apiVersion: v1
kind: Service
metadata:
  name: course-app
  labels:
    app: course-app
spec:
  type: LoadBalancer
  selector:
    app: course-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
